import type { PluginContext } from 'rollup';
import type { AssetSetup } from './AssetComputer';
import type { ChunkSetup } from './ChunkComputer';
import Manager from './Manager';

export type ComputerFn = (this: PluginContext) => any | Promise<any>;
export type ComputerSetup = ChunkSetup | AssetSetup;
export type ComputerSetups = Record<string, ComputerFn | ComputerSetup>;

export interface BaseSetup {
	/**
	 * The computer function.
	 */
	fn: ComputerFn;

	/**
	 * Output filename. Generated by rollup by default, based on the computer's name.
	 */
	fileName?: string;
}

export abstract class Computer {
	public cache?: any | Buffer;

	constructor(
		public name: string,
		public options: BaseSetup,
		public manager: Manager
	) {}

	public async get(): Promise<any> {
		if (this.cache) return this.cache;

		return Promise.resolve(this.options.fn.apply(this.manager.rollup));
	}

	get id(): string {
		return `${this.name}.computed`;
	}
}
